### ISSUE TITLE
Autoclear can't be disabled

### ISSUE THREAD

**Issue by loranger** [ayamflow/image-progress#3]
Instanciating using

``` javascript
var progress = new Progress(url,  {
    autoclear: false
});
```

will still autoclear the XMLHttpRequest beacause of this condition :

``` javascript
this.options.autoclear = this.options.autoclear || true;
```

This should be fixed using #2

**Comment by loranger** [comment]
#2 seems merged

**Comment by ayamflow** [comment]
Damn, I have no memory of seeing or merging this. I guess I did...

**Comment by loranger** [comment]
Sure you did ! ;)

And three years later, I definitely cannot blame you for not remembering 😛
